{
  lib,
  config,
  inputs,
  ...
}:
let
  cfg = config.myHome.bundles.plasma6-desktop;
in
{
  imports = [
    inputs.plasma-manager.homeManagerModules.plasma-manager
  ];

  options.myHome.bundles.plasma6-desktop = with lib; {
    enable = mkEnableOption "Enable plasma6 config";
  };

  config = lib.mkIf cfg.enable {
    #stylix.targets.kde.enable = false; # Sadly plasma and stylix seem to be fucked
    programs.plasma = {
      enable = false;
      # https://nix-community.github.io/plasma-manager/options.xhtml
      workspace = {
        lookAndFeel = "stylix";
        colorScheme = "untitled"; # Scheme generated by stylix
      };
    };

  };
}
